# Generated by update-formula.sh -- do not hand-edit.
# Every sha256 below is the hash of bytes actually downloaded from the url, at
# the moment this file was written, and those bytes were matched against the
# release's own latest-mac.yml. See update-formula.sh for why.

cask "undercontrol" do
  arch arm: "arm64", intel: "x64"

  version "0.162.0"
  sha256 arm:   "6b3920de32277939b12a501b3578ac50d7699812e700ed6915c8a57e77ac3b54",
         intel: "4ad86a0cc55ae69b4aaaac38a4ae92028a53625a098da97d27443c9e863078e3"

  url "https://dl.udctl.com/releases/#{version}/undercontrol-desktop-#{version}-#{arch}.dmg"
  name "UnDercontrol"
  desc "Self-hostable workspace for tasks, notes and expenses with a kubectl-style CLI"
  homepage "https://udctl.com/"

  livecheck do
    url "https://dl.udctl.com/releases/latest/latest-mac.yml"
    strategy :electron_builder
  end

  depends_on macos: :monterey

  app "UnDercontrol.app"

  zap trash: [
    "~/Library/Application Support/undercontrol-desktop",
    "~/Library/Preferences/com.undercontrol.app.plist",
    "~/Library/Saved Application State/com.undercontrol.app.savedState",
  ]
end
