# Generated by update-formula.sh -- do not hand-edit.
# Every sha256 below is the hash of bytes actually downloaded from the url, at
# the moment this file was written, and those bytes were matched against the
# release's own latest-mac.yml. See update-formula.sh for why.

cask "undercontrol" do
  arch arm: "arm64", intel: "x64"

  version "0.161.2"
  sha256 arm:   "f385d90c6581c8253f01507dc5ef26bd031df46bee38faa6eea10c6f75ff310d",
         intel: "c5312d711d9df301921bb9340ea5470bae352138bb1475a41cf0955fd2c1ab2d"

  url "https://dl.udctl.com/releases/#{version}/undercontrol-desktop-#{version}-#{arch}.dmg"
  name "UnDercontrol"
  desc "Desktop app for udctl tasks, notes and AI agents"
  homepage "https://udctl.com/"

  livecheck do
    url "https://dl.udctl.com/releases/latest/latest-mac.yml"
    strategy :electron_builder
  end

  depends_on macos: :monterey

  app "UnDercontrol.app"

  zap trash: [
    "~/Library/Application Support/undercontrol-desktop",
    "~/Library/Preferences/com.undercontrol.app.plist",
    "~/Library/Saved Application State/com.undercontrol.app.savedState",
  ]
end
