# typed: false
# frozen_string_literal: true

# Generated by update-formula.sh -- do not hand-edit.
# Every sha256 below is the hash of bytes actually downloaded from the url above
# it, at the moment this file was written, and those bytes were matched against
# npm's own dist.integrity. See update-formula.sh for why.

class UdServer < Formula
  desc "Self-hosted UnDercontrol server - tasks, notes and the web app in one binary"
  homepage "https://udctl.com/"
  license :cannot_represent

  # The same per-platform tarball npm installs for @oatnil/ud-server, so brew and
  # npm users run identical bytes. It unpacks to package/, which brew steps into.
  on_macos do
    on_arm do
      url "https://registry.npmjs.org/@oatnil/ud-server-darwin-arm64/-/ud-server-darwin-arm64-0.161.2.tgz"
      sha256 "d8b44a4ed2537b7cfe06773e21bcca7e5e442b64a9e9b603c0c1b80c9653d1d1"
    end
    on_intel do
      url "https://registry.npmjs.org/@oatnil/ud-server-darwin-x64/-/ud-server-darwin-x64-0.161.2.tgz"
      sha256 "bc3559de07ab34b040d6199365224292bc8f6673b3ac6641133ddff6e2d82821"
    end
  end

  on_linux do
    on_arm do
      url "https://registry.npmjs.org/@oatnil/ud-server-linux-arm64/-/ud-server-linux-arm64-0.161.2.tgz"
      sha256 "25af23f14a627d2a0258bdce56b911a87c63cc1e53921d77286f0dfb75876d01"
    end
    on_intel do
      url "https://registry.npmjs.org/@oatnil/ud-server-linux-x64/-/ud-server-linux-x64-0.161.2.tgz"
      sha256 "f267ada927b9dd5ae2cec55d3949e46d52e524ab8cbb30048a881ccc31509d50"
    end
  end

  def install
    bin.install "bin/ud-server"
  end

  # The server loads .env from its working directory and the service runs in
  # etc/ud-server, so that file is the configuration. Real environment variables
  # still win over it. Data lives in var/, outside the keg, so an upgrade never
  # touches data; the .env is only ever created, never rewritten.
  # Writes etc/ud-server/.env on first install only. A brew service is running
  # from the moment the user logs in, so JWT_SECRET is generated per install
  # rather than left at the server's built-in fixed string; mode 600, since the
  # file holds it. Random bytes come from /dev/urandom through od, so nothing
  # beyond a POSIX shell is needed on macOS or Linux.
  # PERSONAL_TIER_PASSWORD is deliberately NOT set: without a license the
  # self-hosted default login is the owner's intended design (2026-10-10, card
  # c507cff5), same as the npm package. Do not "fix" it here.
  # The server cannot be told which address to bind (it listens on ":" + PORT),
  # so it is reachable from the network; that is said in caveats, not hidden.
  # (The script is a literal inside the run step: audit rejects anything else there.)
  post_install_steps do
    mkdir_p "ud-server", base: :var
    mkdir_p "log", base: :var
    mkdir_p "ud-server", base: :etc
    unless_path_exists "ud-server/.env", base: :etc do
      run "/bin/sh", args: ["-c", <<~'SH', "sh", "{{etc}}/ud-server", "{{var}}/ud-server"],
        set -eu
        umask 077
        f="$1/.env"
        [ -e "$f" ] && exit 0
        rnd() { head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; }
        {
          echo "# ud-server configuration, read at start by: brew services start ud-server"
          echo "# Edit, then: brew services restart ud-server"
          echo "# Every key is also a CLI flag / env var; see ud-server -h."
          echo "# Generated once at install; brew upgrade never rewrites this file."
          echo
          echo "PORT=8080"
          echo "# The URL users reach this server at. Change it when exposing beyond localhost."
          echo "HOST_DOMAIN=http://localhost:8080"
          echo "UD_DATA_PATH=$2"
          echo
          echo "# Signs login tokens. Generated for this install; keep this file private."
          echo "JWT_SECRET=$(rnd 32)"
        } > "$f.tmp"
        mv "$f.tmp" "$f"
      SH
                     writable_paths: ["ud-server"], writable_base: :etc
    end
  end

  def caveats
    <<~EOS
      Configuration: #{etc}/ud-server/.env
      Data:          #{var}/ud-server
      Logs:          #{var}/log/ud-server.log

      Start now and at login:  brew services start ud-server
      Then open http://localhost:8080 (personal@undercontrol.local / personal123).
      After adding a license (LICENSE_TOKEN) to that file, the server runs as Pro and
      requires ADMIN_EMAIL and ADMIN_PASSWORD there too; log in with those instead.

      The server listens on all network interfaces, not only localhost, so other
      machines on your network can reach port 8080. To serve them on purpose, set
      HOST_DOMAIN in that file to the URL they use, then brew services restart ud-server.
    EOS
  end

  service do
    run opt_bin/"ud-server"
    working_dir etc/"ud-server"
    keep_alive true
    log_path var/"log/ud-server.log"
    error_log_path var/"log/ud-server.log"
  end

  test do
    port = free_port
    (testpath/"data").mkpath
    pid = spawn({ "PORT" => port.to_s, "HOST_DOMAIN" => "http://localhost:#{port}",
                  "UD_DATA_PATH" => (testpath/"data").to_s, "UD_CONFIG_FILE_DISCOVERY" => "false" },
                bin/"ud-server", out: File::NULL, err: File::NULL)
    begin
      out = ""
      30.times do
        sleep 1
        out = Utils.popen_read("curl", "-fs", "http://127.0.0.1:#{port}/api/v1/version")
        break if out.include?(version.to_s)
      end
      assert_match "\"version\":\"#{version}\"", out
    ensure
      Process.kill("TERM", pid)
      Process.wait(pid)
    end
  end
end
