# typed: false
# frozen_string_literal: true

# Generated by update-formula.sh -- do not hand-edit.
# Every sha256 below is the hash of bytes actually downloaded from the url above
# it, at the moment this file was written. See update-formula.sh for why.

class Ud < Formula
  desc "AI agent CLI for udctl - tasks, notes and expenses from the terminal"
  homepage "https://udctl.com/docs/cli/"
  version "0.159.0"
  license :cannot_represent

  # url/sha256 only in the platform blocks, and ONE class-level def install.
  # A def install nested inside an on_arm/on_intel block installs fine but fails
  # brew audit ("Do not define methods in blocks") -- four times, once per block.
  # The filename the archive unpacks to is derivable, so derive it.
  on_macos do
    on_arm do
      url "https://pub-35d77f83ee8a41798bb4b2e1831ac70a.r2.dev/cli/releases/0.159.0/ud_0.159.0_darwin_arm64.tar.gz"
      sha256 "49166fe58fa41e104bca01cf41f1e063762dc56b0afa4af3a36301de2cfcc486"
    end
    on_intel do
      url "https://pub-35d77f83ee8a41798bb4b2e1831ac70a.r2.dev/cli/releases/0.159.0/ud_0.159.0_darwin_amd64.tar.gz"
      sha256 "733a5d2b275ed4135e88fe4b70774e32fb4bf5641e275cc1688e534239420bad"
    end
  end

  on_linux do
    on_arm do
      url "https://pub-35d77f83ee8a41798bb4b2e1831ac70a.r2.dev/cli/releases/0.159.0/ud_0.159.0_linux_arm64.tar.gz"
      sha256 "244ab01d57a1e87cb3d2e7ee6d1bc52b4fb746721a322cf94a4bdbdd7183a245"
    end
    on_intel do
      url "https://pub-35d77f83ee8a41798bb4b2e1831ac70a.r2.dev/cli/releases/0.159.0/ud_0.159.0_linux_amd64.tar.gz"
      sha256 "a14194858ce76b4fda79d2232e74a9f01ef03e742d5c0dcff1d5fa3c5ed5f9af"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "ud_#{version}_#{os}_#{arch}" => "ud"
    # The product is called udctl; the command itself stays ud. Ship both names off
    # the one binary so "which udctl" resolves after a plain brew install ud.
    # (No backticks in this heredoc -- see the note under it.)
    bin.install_symlink bin/"ud" => "udctl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ud --version")
    # The alias is part of what we ship, so test it, not just the real name.
    assert_match version.to_s, shell_output("#{bin}/udctl --version")
  end
end
