# typed: false
# frozen_string_literal: true

# Generated by update-formula.sh -- do not hand-edit.
# Every sha256 below is the hash of bytes actually downloaded from the url above
# it, at the moment this file was written. See update-formula.sh for why.

class Ud < Formula
  desc "UnDercontrol CLI - task and expense management from the terminal"
  homepage "https://oatnil.com/docs/cli/"
  version "0.149.0"
  license :cannot_represent

  # url/sha256 only in the platform blocks, and ONE class-level def install.
  # A def install nested inside an on_arm/on_intel block installs fine but fails
  # brew audit ("Do not define methods in blocks") -- four times, once per block.
  # The filename the archive unpacks to is derivable, so derive it.
  on_macos do
    on_arm do
      url "https://pub-35d77f83ee8a41798bb4b2e1831ac70a.r2.dev/cli/releases/0.149.0/ud_0.149.0_darwin_arm64.tar.gz"
      sha256 "187217148768b8514e3e84884b9b7e7052f3d6ddb0817bf2fbfbf486a2147705"
    end
    on_intel do
      url "https://pub-35d77f83ee8a41798bb4b2e1831ac70a.r2.dev/cli/releases/0.149.0/ud_0.149.0_darwin_amd64.tar.gz"
      sha256 "e7d9759a010b609e431c06ad8de4fc1e0030c3312e970895062cc510e2f5c430"
    end
  end

  on_linux do
    on_arm do
      url "https://pub-35d77f83ee8a41798bb4b2e1831ac70a.r2.dev/cli/releases/0.149.0/ud_0.149.0_linux_arm64.tar.gz"
      sha256 "42590256011247e95f6f651de08f2dde1e2d11fa7131139af8fbbe2781004405"
    end
    on_intel do
      url "https://pub-35d77f83ee8a41798bb4b2e1831ac70a.r2.dev/cli/releases/0.149.0/ud_0.149.0_linux_amd64.tar.gz"
      sha256 "49d004db3519aeb3a085305560e48acfb72c272f19d5b9bb4d87e1cdcd3b1a65"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "ud_#{version}_#{os}_#{arch}" => "ud"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ud --version")
  end
end
