# typed: false
# frozen_string_literal: true

# Generated by update-formula.sh -- do not hand-edit.
# Every sha256 below is the hash of bytes actually downloaded from the url above
# it, at the moment this file was written. See update-formula.sh for why.

class Ud < Formula
  desc "UnDercontrol CLI - task and expense management from the terminal"
  homepage "https://oatnil.com/docs/cli/"
  version "0.150.0"
  license :cannot_represent

  # url/sha256 only in the platform blocks, and ONE class-level def install.
  # A def install nested inside an on_arm/on_intel block installs fine but fails
  # brew audit ("Do not define methods in blocks") -- four times, once per block.
  # The filename the archive unpacks to is derivable, so derive it.
  on_macos do
    on_arm do
      url "https://pub-35d77f83ee8a41798bb4b2e1831ac70a.r2.dev/cli/releases/0.150.0/ud_0.150.0_darwin_arm64.tar.gz"
      sha256 "e18e2d2a026a074e8d8aabd4e6956190b485405799512636a7e26998abe754a1"
    end
    on_intel do
      url "https://pub-35d77f83ee8a41798bb4b2e1831ac70a.r2.dev/cli/releases/0.150.0/ud_0.150.0_darwin_amd64.tar.gz"
      sha256 "95860bd0bd597c93c59aadee681eb00445437503ec4a539e9eae76656bd2d4bc"
    end
  end

  on_linux do
    on_arm do
      url "https://pub-35d77f83ee8a41798bb4b2e1831ac70a.r2.dev/cli/releases/0.150.0/ud_0.150.0_linux_arm64.tar.gz"
      sha256 "2ed04cdf522479ecaf9ef9c2f24ff6068799f3c9315957708b3a3726c2c9c3be"
    end
    on_intel do
      url "https://pub-35d77f83ee8a41798bb4b2e1831ac70a.r2.dev/cli/releases/0.150.0/ud_0.150.0_linux_amd64.tar.gz"
      sha256 "479ee54cfce0d933af0d3cddf7121bba7542855bbb09e8d83ffca8f320de5cec"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "ud_#{version}_#{os}_#{arch}" => "ud"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ud --version")
  end
end
